language: node_js
node_js:
  - '10'
sudo: required
cache:
  directories:
    - $HOME/.npm
script:
  - npm install
after_success:
  - ng deploy --repo=https://${GITHUB_TOKEN}@github.com/kiwsan/angular-ngrx-todo.git --base-href="https://kiwsan.github.io/angular-ngrx-todo/"
